create database poo;
show databases;
use poo;
create table StudentData(id int,name varchar(20),age int);
desc StudentData;
alter table StudentData add MobNo varchar(20);
alter table StudentData drop MobNo;
alter table StudentData modify column MobNo int;
drop table StudentData;
create table Atable(col1 varchar(20),col2 char(20));
insert into Atable values  ('abc','abc');
select length(col1),length(col2) from Atable;
desc Atable;
drop table Atable;
insert into StudentData values (183,'Ritesh',20,8073894);
insert into StudentData values (188,'Roshan',20,9898);
insert into StudentData values (204,'Pranay',20,90457495);
select * from StudentData;
truncate table StudentData;
create table games(name varchar(20),price int,genre varchar(20));                                                                                           
insert into games values('Minecraft',1800,'horror');
insert into games values('gta V',1500,'open world'),('pubg',0,'survival'),('ff',0,'chintu');
insert into games(name) values('dr.driving');
desc table games;
select * from games;
update games set price=1900 where name='gta V';
delete from games where price='0';
delete from games;
drop table games;
select *from games where price='0';
select name from games;
select name from games where price='0';

create table student(sid int,name varchar(20),age int,department varchar(20));
create table courses(cid varchar(10),cname varchar(10),credits int);
create table enrollment(sid int,cid varchar(10));
insert into courses values('bcs101','dsa',3),('bcs102','dms',4),('bec122','gg',2),('bis134','we',3),('bme120','tt',4),('bci134','qq',2);
insert into enrollment values('cs188','bcs101'),('cs183','bcs102'),('ec120','bec122'),('is166','bis134'),('me133','bme120'),('ci140','bci134');
select *from courses;
select *from students;
select *from students where department='cse';
select sid,sname from students where age=20;

#EXP 1
create table Employee(empno int,ename varchar(20),job varchar(20),manager_no int,sal decimal(10,2),commission decimal(10,2));
start transaction;
insert into Employee value(2,'roshan','youtuber',2003,9000000.32,644565),(1,'chintu','youtuber',234,8000980.11,3345),(3,'rakshit','vloger',23343,4522553.34,533);
select *from Employee;
rollback;
select *from Employee;
desc Employee;
alter table Employee add primary key(empno);
alter table Employee modify ename varchar(20) not null;
alter table Employee modify job varchar(20) not null;
alter table Employee modify sal varchar(20) not null;
drop table Employee;
